name: SimplePlayTime
version: '${project.version}'
main: lol.hyper.simpleplaytime.SimplePlayTime
api-version: 1.18
author: hyperdefined
description: Super simple playtime tracking.
commands:
  playtime:
    usage: /playtime
    description: See your playtime.
    permission: simpleplaytime.command
permissions:
  simpleplaytime.command:
    description: Allows the usage of /playtime.
    default: true
  simpleplaytime.reload:
    description: Allows the usage of /playtime reload.
    default: op