name: SimplePlayTime
version: '${project.version}'
main: lol.hyper.simpleplaytime.SimplePlayTime
api-version: 1.18
author: hyperdefined
description: Super simple playtime tracking.
commands:
  playtime:
    usage: /playtime
    description: See your playtime.

libraries:
  - lol.hyper:github-release-api:1.0.1
  - net.kyori:adventure-text-minimessage:4.11.0
  - net.kyori:adventure-platform-bukkit:4.1.0