name: SimplePlayTime
version: '${project.version}'
main: lol.hyper.simpleplaytime.SimplePlayTime
api-version: 1.21
author: hyperdefined
description: Super simple playtime tracking.
website: https://github.com/hyperdefined/SimplePlayTime/
folia-supported: true
commands:
  playtime:
    usage: /playtime
    description: See your playtime.
    permission: simpleplaytime.command
permissions:
  simpleplaytime.command:
    description: Allows the usage of /playtime.
    default: true
  simpleplaytime.reload:
    description: Allows the usage of /playtime reload.
    default: op
  simpleplaytime.reset:
    description: Allows the usage of /playtime reset.
    default: op
  simpleplaytime.add:
    description: Allows the usage of /playtime add.
    default: op